
-- # 1 Database Exploration 
-- Explore all project in the Database 
select * from INFORMATION_SCHEMA.TABLES ;


-- Expolre All columns in a database 
select * from INFORMATION_SCHEMA.COLUMNS
where table_name = 'dim_customer' ;

-- ===============================================================================
-- #2 Dimension Exploration
-- Explore countries our customers come from.
select distinct country 
from dbo.dim_customers ;

-- Explore all categorirs "The Major Division"
select distinct category,subcategory, product_name from dbo.dim_products
order by 1, 2, 3 ;

-- ===============================================================================
-- # 3 Date Exploration
-- Find the date of the first and last order
select 
    min(order_date) first_order_date ,
    max(order_date) as last_order_date,
    DATEDIFF(year,min(order_date),max(order_date)) as order_range_year,
    DATEDIFF(month,min(order_date),max(order_date)) as order_month_year
from dbo.fact_sales ;

-- Find the yougest and the oldest customer 
select
    min(birthdate) first_order_date ,
    datediff(year,min(birthdate),Getdate()) as Oldest_year,
    datediff(year,max(birthdate),Getdate()) as Youger_year,
    max(birthdate) as last_order_date
from dbo.dim_customers ;

-- ===============================================================================
-- # 4 Measure Exploration
-- Find the total sales
-- Find how many items are sold 
-- Find the averafe selling price
-- Find the total number of orders
-- Find the total number of product
-- Find the total number of customers
-- Find the total number of customers that has placed an order
SELECT 
    SUM(sales_amount) AS TotalSales,
    SUM(quantity) AS TotalItemsSold,
    AVG(price) AS AverageSellingPrice,
    COUNT(DISTINCT order_number) AS TotalOrders,
    COUNT(DISTINCT product_key) AS TotalProducts,
    COUNT(DISTINCT customer_key) AS TotalCustomers,
    COUNT(DISTINCT CASE WHEN customer_key IS NOT NULL THEN customer_key END) AS CustomersWithOrders
FROM 
    dbo.fact_sales;

-- Generate report a report that shoe all key metrics of the business
select 'TotalSales' as mearsure_name,Sum(sales_amount) as measure_value from dbo.fact_sales
    union all
select 'TotalItemsSold' as mearsure_name,Sum(quantity) as measure_value from dbo.fact_sales
    union all
select 'AverageSellingPrice' as mearsure_name,AVG(price) as measure_value from dbo.fact_sales
    union all
select 'TotalOrders' as mearsure_name,COUNT(DISTINCT product_key) as measure_value from dbo.fact_sales
    union all
select 'TotalProducts' as mearsure_name,COUNT(DISTINCT customer_key) as measure_value from dbo.fact_sales
    union all
select 'CustomersWithOrders' as mearsure_name, COUNT(DISTINCT CASE WHEN customer_key IS NOT NULL THEN customer_key END) measure_value from dbo.fact_sales;

-- ===============================================================================
-- #5 Magnitude Exploration
-- Find total customers by countries
select 
    country,count(customer_key) as total_customers
from dbo.dim_customers
group by country 
order by total_customers desc ;

-- Find total customers by gender
select 
    gender,count(customer_key) as total_customers_gender
from dbo.dim_customers
group by gender
order by total_customers_gender desc ;

-- Find total products by category
select
    category, count(product_key) as count_product
from dbo.dim_products
group by category
order by count_product desc ;

-- What is the average costs in each category?
select
    category,avg(cost) as avg_cost
from dbo.dim_products
group by category   
order by avg_cost desc ;

-- What is the total revenue generated for each category?
select 
    p.category,
    sum(sales_amount) as sum_sales
from dbo.fact_sales as f
left join dbo.dim_products as p
    on f.product_key = p.product_key
group by p.category
order by sum_sales desc ;

-- Find total revenue is generated by each customer
select 
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(sales_amount) as total_revenue
from dbo.fact_sales as f
left join dbo.dim_customers as c
    on f.customer_key = c.customer_key
group by 
        c.customer_key,
        c.first_name,
        c.last_name
order by total_revenue desc ;
 
-- What is the distribution of sold items across countries?
select 
    c.country,
    sum(f.quantity) as total_sold_items
from dbo.fact_sales as f
left join dbo.dim_customers as c
    on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc ;
 

-- ===============================================================================
-- # 6 Ranking TOP-N BOTTOM-N
-- Which 5 products generate the highest revenue?
select top 5 
    p.product_name,
    sum(s.sales_amount) as hightest_revenue
from dbo.fact_sales as s
left join dbo.dim_products as p
    on s.product_key = p.product_key
group by p.product_name
order by hightest_revenue desc ;

-- What are the 5 worst-performing products in terms of sales?
select top 5 
    p.product_name,
    sum(s.sales_amount) as hightest_revenue
from dbo.fact_sales as s
left join dbo.dim_products as p
    on s.product_key = p.product_key
group by p.product_name
order by hightest_revenue ;

-- With Window function is more complitate
select *
from (
select 
    p.product_name,
    sum(s.sales_amount) as hightest_revenue,
    ROW_NUMBER() over(order by sum(s.sales_amount) desc) as rank_products
from dbo.fact_sales as s
left join dbo.dim_products as p
    on s.product_key = p.product_key
group by  p.product_name 
) t 
where rank_products < = 5 ;

-- Find the top 10 customers who have generated the highest revenue
select Top 10
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(sales_amount) as highest_revenue
from dbo.fact_sales as s
left join dbo.dim_customers as c
on s.customer_key = c.customer_key
group by  
    c.customer_key,
    c.first_name,
    c.last_name
order by highest_revenue desc

-- The 3 customers with the fewest orders placed
select Top 3
    c.customer_key,
    c.first_name,
    c.last_name,
    count(distinct(s.order_number)) as total_order
from dbo.fact_sales as s
left join dbo.dim_customers as c
on s.customer_key = c.customer_key
group by  
    c.customer_key,
    c.first_name,
    c.last_name
order by total_order
















